### ISSUE TITLE
[ValueError: axes don't match array] in the "imgs.transpose((0, 3, 1, 2))" line

### ISSUE THREAD

**Issue by flipflop98** [mseitzer/pytorch-fid#1]
Hello all,
I used following command to calculate FID distance from two different folders.
: ./fid_score.py /data/vision/pytorch-CycleGAN-and-pix2pix/datasets/synthia2kitti_ex1/testAB /data/vision/pytorch-CycleGAN-and-pix2pix/datasets/synthia2kitti_ex1/testB

I've come across the error as follows.
:Traceback (most recent call last):
  File "./fid_score.py", line 262, in <module>
    args.dims)
  File "./fid_score.py", line 249, in calculate_fid_given_paths
    dims, cuda)
  File "./fid_score.py", line 223, in _compute_statistics_of_path
    imgs = imgs.transpose((0, 3, 1, 2))
ValueError: axes don't match array

Please give me any comment.
Thank you.

**Comment by Alpaca07** [comment]
The sizes of the images in one path must be all the same. When I resized all the images to the same size, the problem has been solved.

**Comment by iamzhangyunlu** [comment]
> The sizes of the images in one path must be all the same. When I resized all the images to the same size, the problem has been solved.

Hi,
if the sizes of two different folders are different, is it ok?
In short, the size of true images and the size of generated images must be the same? @Alpaca07 @mseitzer

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale image you can simply expand the dimension of your image. This happens because PIL Image will give you 2 dimension output if it is grayscale image. Please add comments if there's anything wrong in my comment.

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale image you can simply expand the dimension of your image. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))Please add comments if there's anything wrong in my comment.

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale image you can simply expand the dimension of your image. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))Please add comments if there's anything wrong in my comment.

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale images you can simply expand the dimension of your images. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64)) Please add comments if there's anything wrong in my comment.

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale images you can simply expand the dimension of your images. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64)) Please add comments if there's anything wrong in my comment. @mseitzer

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale images you can simply expand the dimension of your images. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64)) Please add comments if there's anything wrong in my comment. @mseitzer

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale images you can simply expand the dimension of your images. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64)) Please add comments if there's anything wrong in my comment. @mseitzer

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale images you can simply expand the dimension of your images. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))

Please add comments if there's anything wrong in my comment. @mseitzer

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale images you can simply expand the dimension of your images after you load. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))

Please add comments if there's anything wrong in my comment. @mseitzer

**Comment by dragonHyeon** [comment]
> this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.

Or if you just want to use grayscale images you can simply expand the dimension of your images after you load them. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))

Please add comments if there's anything wrong in my comment. @mseitzer

**Comment by dragonHyeon** [comment]
> > this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.
> 
> Or if you just want to use grayscale images you can simply expand the dimension of your images after you load them. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))
> 
> Please add comments if there's anything wrong in my comment. @mseitzer

I found out this code eventually requires 3 channel inputs later, so we shouldn't give 1 channel input.

**Comment by dragonHyeon** [comment]
> > this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.
> 
> Or if you just want to use grayscale images you can simply expand the dimension of your images after you load them. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))
> 
> Please add comments if there's anything wrong in my comment. @mseitzer

I found out this code eventually requires 3 channel inputs later, so we should change to 3 channel input anyway.

**Comment by dragonHyeon** [comment]
> > this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.
> 
> Or if you just want to use grayscale images you can simply expand the dimension of your images after you load them. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))
> 
> Please add comments if there's anything wrong in my comment. @mseitzer

I found out this code eventually requires 3 channel inputs later, so we should change them into 3 channel anyway.

**Comment by dragonHyeon** [comment]
> > this error is likely caused by your images containing grayscale images. A quick fix would be to make sure that your images are in RGB.
> 
> Or if you just want to use grayscale images you can simply expand the dimension of your images after you load them. This happens because PIL Image will give you 2 dimension output if it is grayscale image. (e.g. (64, 64, 1) -> (64, 64))
> 
> Please add comments if there's anything wrong in my comment. @mseitzer

I found out this code eventually requires 3 channel inputs later, so we should change them into 3 channel anyway.

**Comment by wjbKimberly** [comment]
Hi, do you get results now. I wonder is there any mistakes in my reimplement. The FID score seems too large.
I get results of FID: 111.83639814314319 using given "facades_label2photo_pretrained" checkpoint.

**Comment by parthrangarajan** [comment]
Even after I resized the images to 512 from 1024 and had all of the images in the same directory I am still getting this error. 
```
dataset_path = "/content/drive/MyDrive/landscape_pngs"
#give your dataset a name
dataset_name = "landscape_images"

#you don't need to edit anything here
!python /content/stylegan/dataset_tool.py create_from_images /content/drive/MyDrive/landscape_images {dataset_path}
```
I am trying to train the styleGAN on custom images. Any help would be deeply appreciated. I'll share the notebook I am working on here. 
Colab Notebook link : https://colab.research.google.com/drive/1sQG3_orw5NBk_gIrabp6RvRGlkIl7qkA?usp=sharing
The link for the zipped file of the dataset is here : https://drive.google.com/file/d/1iylHPQrNs1dtu-miHJXSbS8WXdGEXTO4/view?usp=sharing
