### ISSUE TITLE
RuntimeWarning: invalid value encountered in double_scalars   arg2 = norm(X.dot(X) - A, 'fro')**2 / norm(A, 'fro')

### ISSUE THREAD

**Issue by thinkerthinker** [mseitzer/pytorch-fid#10]
I am getting this error when testing a model.
RuntimeWarning: invalid value encountered in double_scalars arg2 = norm(X.dot(X) - A, 'fro')**2 / norm(A, 'fro')
I did not find a solution.

**Comment by mseitzer** [comment]
I don't think I can help you there, and I don't even know where this line of code shows up.
