### ISSUE TITLE
FID score for Mnist

### ISSUE THREAD

**Issue by zzqiuzz** [mseitzer/pytorch-fid#12]
Hi! Thanks for your work.May i have you instruction on how to calculate FID score for Mnist dataset which has only 1 channels ,no idea to solve it now.Thanks.

**Comment by mseitzer** [comment]
Generally, if inputting grayscale images into RGB networks, you would just copy the grayscale channel three times. However, it is unclear how FID behaves in this case, as the original Inception network was probably not trained on grayscale images. 

Also, I would advise against computing a FID score on Mnist. FID score was designed to work on larger images of natural scenes, not on 28x28 images of handwritten digits. I am guessing that the numbers you would get from that are pretty meaningless and do not reflect human judgement of quality.

**Comment by saurabheights** [comment]
I added more info here :- https://stackoverflow.com/questions/57183647/ 
FYI: Thanks for your repo. Helped me finish this task fast.
