### ISSUE TITLE
nested numpy array rather than 2d array

### ISSUE THREAD

**Issue by JiaBob** [mseitzer/pytorch-fid#21]
Because imread is deprecated from scipy 1.3, i use imread from matplotlib instead. But problem occurs on the line:
`images = np.array([imread(str(f)).astype(np.float32) for f in files[start:end]])`
It returns a nested numpy array, likes array([array([...]), ...]), rather than 2d array. To make the code precise, do you know how to convert the nested array to 2d numpy array?

**Comment by mseitzer** [comment]
I would recommend using [imageio](https://imageio.github.io/) instead of matplotlib to read images. It has the same interface as the old `scipy.misc.imread` method. At some point, I will switch to this in the code as well.

**Comment by JiaBob** [comment]
Thanks for you reply.
The reason for this issue is not just what I said. After debuging, I found it is because the image size is not same. All matplotlib, imageio and even skimage work! Hence, I rewrite it into pytorch ImageFolder and doing the data preprocessing in the pytorch way. The preprocess includes the resize. 
By the way, I find there are only options for using gpu or not. So I change it to be able to select specific device.  
I can pull the modified version to yours, if you wish.

**Comment by mseitzer** [comment]
Thank you, but there is already a PR pending for including Pytorch-style data loading. If you want, you could submit a PR regarding choosing a specific device.
