### ISSUE TITLE
scipy.misc.imread is deprecated

### ISSUE THREAD

**Issue by jkyl** [mseitzer/pytorch-fid#25]
First, thank you for the high-quality implementation! 

## Problem
`scipy.misc.imread` was deprecated in SciPy 1.0.0, and was removed in 1.2.0. Nevertheless `fid_score.py` imports this function. This will fail unless the user downgrades their SciPy. 

## Potential solutions
SciPy recommends using `imageio.imread` instead. Another alternative is `np.asarray(PIL.Image.open(...))`. If you have a preference for which dependency you'd like to add, I will submit a PR. 

All best,
Jon

**Comment by mseitzer** [comment]
Thank you for being willing to provide a PR. I guess I would slightly prefer to use `np.asarray(PIL.Image.open(...))`, just to avoid adding another dependency. 

Of course, we need to make sure that `np.asarray(PIL.Image.open(...))` returns the same thing as `scipy.misc.imread`.

**Comment by jkyl** [comment]
I will get on it!

**Comment by jkyl** [comment]
https://github.com/mseitzer/pytorch-fid/pull/27

**Comment by mseitzer** [comment]
Thanks. Merged #27.
