### ISSUE TITLE
Very long model building time

### ISSUE THREAD

**Issue by ParthaEth** [mseitzer/pytorch-fid#28]
I use you module as follows

from my_utils.pytorch_fid import fid_score

 def load_inception_model(self, dims):
     block_idx = fid_score.InceptionV3.BLOCK_INDEX_BY_DIM[dims]
     self.model = fid_score.InceptionV3([block_idx])
     self.model.cuda()
     self.model.eval()

But this load function takes a very long time. I think this is coupled with pytorch upgrade. However I am not sure. Can you make some comments?

**Comment by mseitzer** [comment]
This is a known bug and related to a change in scipy (see https://github.com/pytorch/vision/issues/1797). They have a fix in torchvision in master, but it is not yet in a released version. Once it is, we can adopt the fix here as well. 

For now, a workaround for you to try is to downgrade scipy from `1.4.1` to `1.3.1`.
