### ISSUE TITLE
"the magnitude of the FID score" 

### ISSUE THREAD

**Issue by pytyeah** [mseitzer/pytorch-fid#30]
Thanks for your great work!
And I have a question now. You said ''Note that this changes the magnitude of the FID score '',and what exactly does this mean?
Waiting for your reply~

**Comment by mseitzer** [comment]
This just means that the numbers computed for the different feature maps can be in different ranges (i.e. for one dimensionality, the FID scores might be 10x smaller than for another). So you should not compare FID scores computed on different feature maps with each other.
