### ISSUE TITLE
 Unexpected key(s) in state_dict: 

### ISSUE THREAD

**Issue by EmilyLike** [mseitzer/pytorch-fid#34]
When the code load the inception model， it appear this kind of error。
./fid_score.py /home/liuyx/dataset/cyclegan/fastblind-test/testA/bike-packing/ /home/liuyx/dataset/cyclegan/fastblind-test/fakeA/bike-packing/fakea/
Traceback (most recent call last):
  File "./fid_score.py", line 262, in <module>
    args.dims)
  File "./fid_score.py", line 242, in calculate_fid_given_paths
    model = InceptionV3([block_idx])
  File "/home/liuyx/codes/pytorch-fid/inception.py", line 80, in __init__
    inception = fid_inception_v3()
  File "/home/liuyx/codes/pytorch-fid/inception.py", line 207, in fid_inception_v3
    inception.load_state_dict(state_dict)
  File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Inception3:
        Unexpected key(s) in state_dict: "Conv2d_1a_3x3.bn.num_batches_tracked", "Conv2d_2a_3x3.bn.num_batches_tracked", "Conv2d_2b_3x3.bn.num_batches_tracked", "Conv2d_3b_1x1.bn.num_batches_tracked", "Conv2d_4a_3x3.bn.num_batches_tracked", "Mixed_5b.branch1x1.bn.num_batches_tracked", "Mixed_5b.branch5x5_1.bn.num_batches_tracked", "Mixed_5b.branch5x5_2.bn.num_batches_tracked", "Mixed_5b.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_5b.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_5b.branch3x3dbl_3.bn.num_batches_tracked", "Mixed_5b.branch_pool.bn.num_batches_tracked", "Mixed_5c.branch1x1.bn.num_batches_tracked", "Mixed_5c.branch5x5_1.bn.num_batches_tracked", "Mixed_5c.branch5x5_2.bn.num_batches_tracked", "Mixed_5c.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_5c.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_5c.branch3x3dbl_3.bn.num_batches_tracked", "Mixed_5c.branch_pool.bn.num_batches_tracked", "Mixed_5d.branch1x1.bn.num_batches_tracked", "Mixed_5d.branch5x5_1.bn.num_batches_tracked", "Mixed_5d.branch5x5_2.bn.num_batches_tracked", "Mixed_5d.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_5d.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_5d.branch3x3dbl_3.bn.num_batches_tracked", "Mixed_5d.branch_pool.bn.num_batches_tracked", "Mixed_6a.branch3x3.bn.num_batches_tracked", "Mixed_6a.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_6a.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_6a.branch3x3dbl_3.bn.num_batches_tracked", "Mixed_6b.branch1x1.bn.num_batches_tracked", "Mixed_6b.branch7x7_1.bn.num_batches_tracked", "Mixed_6b.branch7x7_2.bn.num_batches_tracked", "Mixed_6b.branch7x7_3.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_1.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_2.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_3.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_4.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_5.bn.num_batches_tracked", "Mixed_6b.branch_pool.bn.num_batches_tracked", "Mixed_6c.branch1x1.bn.num_batches_tracked", "Mixed_6c.branch7x7_1.bn.num_batches_tracked", "Mixed_6c.branch7x7_2.bn.num_batches_tracked", "Mixed_6c.branch7x7_3.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_1.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_2.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_3.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_4.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_5.bn.num_batches_tracked", "Mixed_6c.branch_pool.bn.num_batches_tracked", "Mixed_6d.branch1x1.bn.num_batches_tracked", "Mixed_6d.branch7x7_1.bn.num_batches_tracked", "Mixed_6d.branch7x7_2.bn.num_batches_tracked", "Mixed_6d.branch7x7_3.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_1.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_2.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_3.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_4.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_5.bn.num_batches_tracked", "Mixed_6d.branch_pool.bn.num_batches_tracked", "Mixed_6e.branch1x1.bn.num_batches_tracked", "Mixed_6e.branch7x7_1.bn.num_batches_tracked", "Mixed_6e.branch7x7_2.bn.num_batches_tracked", "Mixed_6e.branch7x7_3.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_1.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_2.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_3.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_4.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_5.bn.num_batches_tracked", "Mixed_6e.branch_pool.bn.num_batches_tracked", "Mixed_7a.branch3x3_1.bn.num_batches_tracked", "Mixed_7a.branch3x3_2.bn.num_batches_tracked", "Mixed_7a.branch7x7x3_1.bn.num_batches_tracked", "Mixed_7a.branch7x7x3_2.bn.num_batches_tracked", "Mixed_7a.branch7x7x3_3.bn.num_batches_tracked", "Mixed_7a.branch7x7x3_4.bn.num_batches_tracked", "Mixed_7b.branch1x1.bn.num_batches_tracked", "Mixed_7b.branch3x3_1.bn.num_batches_tracked", "Mixed_7b.branch3x3_2a.bn.num_batches_tracked", "Mixed_7b.branch3x3_2b.bn.num_batches_tracked", "Mixed_7b.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_7b.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_7b.branch3x3dbl_3a.bn.num_batches_tracked", "Mixed_7b.branch3x3dbl_3b.bn.num_batches_tracked", "Mixed_7b.branch_pool.bn.num_batches_tracked", "Mixed_7c.branch1x1.bn.num_batches_tracked", "Mixed_7c.branch3x3_1.bn.num_batches_tracked", "Mixed_7c.branch3x3_2a.bn.num_batches_tracked", "Mixed_7c.branch3x3_2b.bn.num_batches_tracked", "Mixed_7c.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_7c.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_7c.branch3x3dbl_3a.bn.num_batches_tracked", "Mixed_7c.branch3x3dbl_3b.bn.num_batches_tracked", "Mixed_7c.branch_pool.bn.num_batches_tracked".

**Comment by JZakraoui** [comment]
> When the code load the inception model， it appear this kind of error。
> ./fid_score.py /home/liuyx/dataset/cyclegan/fastblind-test/testA/bike-packing/ /home/liuyx/dataset/cyclegan/fastblind-test/fakeA/bike-packing/fakea/
> Traceback (most recent call last):
> File "./fid_score.py", line 262, in
> args.dims)
> File "./fid_score.py", line 242, in calculate_fid_given_paths
> model = InceptionV3([block_idx])
> File "/home/liuyx/codes/pytorch-fid/inception.py", line 80, in **init**
> inception = fid_inception_v3()
> File "/home/liuyx/codes/pytorch-fid/inception.py", line 207, in fid_inception_v3
> inception.load_state_dict(state_dict)
> File "/usr/local/lib/python3.5/dist-packages/torch/nn/modules/module.py", line 721, in load_state_dict
> self.**class**.**name**, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for Inception3:
> Unexpected key(s) in state_dict: "Conv2d_1a_3x3.bn.num_batches_tracked", "Conv2d_2a_3x3.bn.num_batches_tracked", "Conv2d_2b_3x3.bn.num_batches_tracked", "Conv2d_3b_1x1.bn.num_batches_tracked", "Conv2d_4a_3x3.bn.num_batches_tracked", "Mixed_5b.branch1x1.bn.num_batches_tracked", "Mixed_5b.branch5x5_1.bn.num_batches_tracked", "Mixed_5b.branch5x5_2.bn.num_batches_tracked", "Mixed_5b.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_5b.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_5b.branch3x3dbl_3.bn.num_batches_tracked", "Mixed_5b.branch_pool.bn.num_batches_tracked", "Mixed_5c.branch1x1.bn.num_batches_tracked", "Mixed_5c.branch5x5_1.bn.num_batches_tracked", "Mixed_5c.branch5x5_2.bn.num_batches_tracked", "Mixed_5c.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_5c.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_5c.branch3x3dbl_3.bn.num_batches_tracked", "Mixed_5c.branch_pool.bn.num_batches_tracked", "Mixed_5d.branch1x1.bn.num_batches_tracked", "Mixed_5d.branch5x5_1.bn.num_batches_tracked", "Mixed_5d.branch5x5_2.bn.num_batches_tracked", "Mixed_5d.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_5d.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_5d.branch3x3dbl_3.bn.num_batches_tracked", "Mixed_5d.branch_pool.bn.num_batches_tracked", "Mixed_6a.branch3x3.bn.num_batches_tracked", "Mixed_6a.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_6a.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_6a.branch3x3dbl_3.bn.num_batches_tracked", "Mixed_6b.branch1x1.bn.num_batches_tracked", "Mixed_6b.branch7x7_1.bn.num_batches_tracked", "Mixed_6b.branch7x7_2.bn.num_batches_tracked", "Mixed_6b.branch7x7_3.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_1.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_2.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_3.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_4.bn.num_batches_tracked", "Mixed_6b.branch7x7dbl_5.bn.num_batches_tracked", "Mixed_6b.branch_pool.bn.num_batches_tracked", "Mixed_6c.branch1x1.bn.num_batches_tracked", "Mixed_6c.branch7x7_1.bn.num_batches_tracked", "Mixed_6c.branch7x7_2.bn.num_batches_tracked", "Mixed_6c.branch7x7_3.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_1.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_2.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_3.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_4.bn.num_batches_tracked", "Mixed_6c.branch7x7dbl_5.bn.num_batches_tracked", "Mixed_6c.branch_pool.bn.num_batches_tracked", "Mixed_6d.branch1x1.bn.num_batches_tracked", "Mixed_6d.branch7x7_1.bn.num_batches_tracked", "Mixed_6d.branch7x7_2.bn.num_batches_tracked", "Mixed_6d.branch7x7_3.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_1.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_2.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_3.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_4.bn.num_batches_tracked", "Mixed_6d.branch7x7dbl_5.bn.num_batches_tracked", "Mixed_6d.branch_pool.bn.num_batches_tracked", "Mixed_6e.branch1x1.bn.num_batches_tracked", "Mixed_6e.branch7x7_1.bn.num_batches_tracked", "Mixed_6e.branch7x7_2.bn.num_batches_tracked", "Mixed_6e.branch7x7_3.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_1.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_2.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_3.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_4.bn.num_batches_tracked", "Mixed_6e.branch7x7dbl_5.bn.num_batches_tracked", "Mixed_6e.branch_pool.bn.num_batches_tracked", "Mixed_7a.branch3x3_1.bn.num_batches_tracked", "Mixed_7a.branch3x3_2.bn.num_batches_tracked", "Mixed_7a.branch7x7x3_1.bn.num_batches_tracked", "Mixed_7a.branch7x7x3_2.bn.num_batches_tracked", "Mixed_7a.branch7x7x3_3.bn.num_batches_tracked", "Mixed_7a.branch7x7x3_4.bn.num_batches_tracked", "Mixed_7b.branch1x1.bn.num_batches_tracked", "Mixed_7b.branch3x3_1.bn.num_batches_tracked", "Mixed_7b.branch3x3_2a.bn.num_batches_tracked", "Mixed_7b.branch3x3_2b.bn.num_batches_tracked", "Mixed_7b.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_7b.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_7b.branch3x3dbl_3a.bn.num_batches_tracked", "Mixed_7b.branch3x3dbl_3b.bn.num_batches_tracked", "Mixed_7b.branch_pool.bn.num_batches_tracked", "Mixed_7c.branch1x1.bn.num_batches_tracked", "Mixed_7c.branch3x3_1.bn.num_batches_tracked", "Mixed_7c.branch3x3_2a.bn.num_batches_tracked", "Mixed_7c.branch3x3_2b.bn.num_batches_tracked", "Mixed_7c.branch3x3dbl_1.bn.num_batches_tracked", "Mixed_7c.branch3x3dbl_2.bn.num_batches_tracked", "Mixed_7c.branch3x3dbl_3a.bn.num_batches_tracked", "Mixed_7c.branch3x3dbl_3b.bn.num_batches_tracked", "Mixed_7c.branch_pool.bn.num_batches_tracked".

Hi,

I have the same error, do you have any solution? thanks

**Comment by mseitzer** [comment]
I can not reproduce this error. Which version of `pytorch` and `torchvision` are you using? 

As a workaround, you should be able to avoid this error by changing this line
https://github.com/mseitzer/pytorch-fid/blob/011829daeccc84341c1e8e6061d10a640a495573/inception.py#L207

to 

`inception.load_state_dict(state_dict, strict=False)`

**Comment by JZakraoui** [comment]
inception.load_state_dict(state_dict, strict=False) resolves the issue.

Thank you

Am Sa., 13. Juni 2020 um 15:39 Uhr schrieb mseitzer <
notifications@github.com>:
