### ISSUE TITLE
Couldn't work with gray-scale images

### ISSUE THREAD

**Issue by AboMad** [mseitzer/pytorch-fid#35]
Hi, 
I am trying to apply this implementation for grayscale image datasets, but that doesn't work. I think the function imread has to have a condition to convert grayscale images to RGB ones.
https://github.com/mseitzer/pytorch-fid/blob/011829daeccc84341c1e8e6061d10a640a495573/fid_score.py#L68

I've tried to use this:
`def imread(filename):
    """
    Loads an image file into a (height, width, 3) uint8 ndarray.
    """
    img_ = np.asarray(Image.open(filename), dtype=np.uint8)
    if len(img_.shape) < 3:
        img_ = np.asarray(cv2.cvtColor(img_, cv2.COLOR_GRAY2RGB), dtype=np.uint8)      
    return img_[..., :3]
`
But it does not work for me, the resulting Images array has the dimension (batch_size,), and an error occurs when trying to transpose it to the shape (batch_size, 3, hight, width) at line 116
`images = images.transpose((0, 3, 1, 2))`
can you help to overcome this issue, please

**Comment by mseitzer** [comment]
Try to use something like this:

```
def imread(filename):
    return np.asarray(Image.open(filename).convert('RGB'), dtype=np.uint8)[..., :3]
```

**Comment by AboMad** [comment]
Thanks, it works
