### ISSUE TITLE
upload to python package index?

### ISSUE THREAD

**Issue by GetsEclectic** [mseitzer/pytorch-fid#38]
I noticed you merged setup.py but I don't see it in pypi, anything I can help with?

**Comment by mseitzer** [comment]
Yes, this is coming. Sorry for the delay, I am a bit busy at the moment.

**Comment by GetsEclectic** [comment]
No problem, just wanted to make sure you didn't forget :) I'm excited to be
able to use it in a project.

**Comment by mseitzer** [comment]
It's finally available on pip: https://pypi.org/project/pytorch-fid/

Have fun!

**Comment by GetsEclectic** [comment]
Thanks so much, great library!
