### ISSUE TITLE
Is the number of images in both two image folders have to be equal?

### ISSUE THREAD

**Issue by eddiegao1996** [mseitzer/pytorch-fid#45]
Thanks for the great work. I have a question of if the **number of images** in both two image folders have to be equal when calculating the FID score. Because the FID distance is represented as the distance between two normal distributions. Sorry to bother you.

**Comment by mseitzer** [comment]
No, the number of images does not have to be equal. It should be bigger than 2048 in both folders though.

**Comment by eddiegao1996** [comment]
Thanks so much for the clarification.
