### ISSUE TITLE
Get score between a dataset and a single sample

### ISSUE THREAD

**Issue by caesar-one** [mseitzer/pytorch-fid#46]
is there a way to calculate the distance between a dataset and just one sample (instead of a set of them), producing consistent results?

**Comment by mseitzer** [comment]
This is not possible with Frechet Inception Distance. FID computes a distance between two Gaussian distributions. You can not estimate a Gaussian distribution from a single sample.

**Comment by caesar-one** [comment]
Thank you very much for your answer. Actually, our idea is to calculate the FID distance between the two estimated Gaussian distributions and only at a later stage to see how likely specific samples are with respect to these distributions. If the FID distance is high - the two distributions are closed - it may be of some interest to give a score to each sample in terms of coherence with the observed phenomenon probability density.

**Comment by mseitzer** [comment]
Okay, so you want to compute something like the likelihood of a single sample under the target distribution. This is possible, although you will have to do some manual work.

You need to call `fid_score._compute_statistics_of_path` on your target dataset, which returns mean and covariance of the Gaussian. Then, run the Inception net on your single sample to obtain its features. Then compute the likelihood of the features given mean and covariance.

**Comment by caesar-one** [comment]
Okay, it worked! I used SciPy's `multivariate_normal.logpdf` to calculate the likelihood of the features given mean and covariance matrix. Thank you very much!
