### ISSUE TITLE
ValueError: could not broadcast input array from shape (256,256,3) into shape (256)

### ISSUE THREAD

**Issue by xml94** [mseitzer/pytorch-fid#48]
Traceback (most recent call last):
  File "/home/multiai3/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/multiai3/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/__main__.py", line 4, in <module>
    pytorch_fid.fid_score.main()
  File "/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/fid_score.py", line 252, in main
    args.dims)
  File "/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/fid_score.py", line 237, in calculate_fid_given_paths
    dims, cuda)
  File "/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/fid_score.py", line 219, in _compute_statistics_of_path
    dims, cuda)
  File "/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/fid_score.py", line 204, in calculate_activation_statistics
    act = get_activations(files, model, batch_size, dims, cuda)
  File "/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/fid_score.py", line 107, in get_activations
    for f in files[start:end]])
ValueError: could not broadcast input array from shape (256,256,3) into shape (256)

I check that evey image is in 3 channels and 256 * 256 resolution.
What is the problem?

Thanks for the valuable work.

**Comment by mseitzer** [comment]
I suspect that one of your images fails to load into a weird shape by PIL. To check if this is the case, you could insert something like

```
shapes = [imread(str(f)).shape for f in files]
print(shapes)
```

before the loop (e.g. line 101) into `/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/fid_score.py`, and verify that they really all have the correct `(256,256,3)` shape.

**Comment by xml94** [comment]
> I suspect that one of your images is decoded to a weird shape by PIL. To check if this is the case, you could insert something like
> 
> ```
> shapes = [imread(str(f)).shape for f in files]
> print(shapes)
> ```
> 
> before the loop (e.g. line 101) into `/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/fid_score.py`, and verify that they really all have the correct `(256,256,3)` shape.

Thanks for your reply.

I added as you suggested like below:
`for i in shapes:
      if i != (256, 256, 3):
        print(i)`

and there are several images have this shape but wo weird:
(256, 3)
(256, 3)
(256, 3)
(256, 3)
(256, 3)
(256, 3)
(256, 3)

I am curious what happened?

**Comment by xml94** [comment]
> I suspect that one of your images is decoded to a weird shape by PIL. To check if this is the case, you could insert something like
> 
> ```
> shapes = [imread(str(f)).shape for f in files]
> print(shapes)
> ```
> 
> before the loop (e.g. line 101) into `/home/multiai3/anaconda3/lib/python3.7/site-packages/pytorch_fid/fid_score.py`, and verify that they really all have the correct `(256,256,3)` shape.

I checked again and found that there are images in gray instead of RGB image and so there are in (256, 256).

In this case, I rewrite your code to support the case like below (from line 99 to the loop)
`
files_ = []
    for i in files:
      shape = imread(str(i)).shape
      if shape != (256, 256, 3):
        print('Please attention this image is in gray : {}'.format(i))
      else:
        files_.append(i)
    files = files_
    pred_arr = np.empty((len(files), dims))
    shapes = [imread(str(f)).shape for f in files]
`

Then I successfully got desired results.

Thanks again for your code and your valuable reply.
