### ISSUE TITLE
Making it compatible for other image extensions as well

### ISSUE THREAD

**Issue by ayush1801** [mseitzer/pytorch-fid#50]
please add the 'jpeg' etc. image extensions as well to reduce the time for saving the entire datasets into 'jpg' or 'png' extensions.

**Comment by mseitzer** [comment]
Good point. Any other extensions you have in mind?

**Comment by ayush1801** [comment]
Thanks! We may consider these : 
IMG_EXTENSIONS = (
    '.jpg',
    '.jpeg',
    '.png',
    '.ppm',
    '.bmp',
    '.pgm',
    '.tif',
    '.tiff',
    '.webp',
)

**Comment by ayush1801** [comment]
Please add these extra extensions, otherwise, I have to save my dataset into compatible extension one.  Thanks in advance
