### ISSUE TITLE
Installation doesn't work

### ISSUE THREAD

**Issue by pocaha** [mseitzer/pytorch-fid#54]
Hi,

first and foremost thank you very much for your work! I have an installation problem: The shell gives me following output:
ERROR: Command errored out with exit status 1:
command: 'C:\Users\bibi\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\Users\bibi\AppData\Local\Temp\pip-install-ma3x6o5s\pytorch-fid_20cb67d1201c4ad9ae07a1faa01a3199\setup.py'"'"'; file='"'"'C:\Users\bibi\AppData\Local\Temp\pip-install-ma3x6o5s\pytorch-fid_20cb67d1201c4ad9ae07a1faa01a3199\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(file);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\bibi\AppData\Local\Temp\pip-pip-egg-info-y5m73gya'
cwd: C:\Users\bibi\AppData\Local\Temp\pip-install-ma3x6o5s\pytorch-fid_20cb67d1201c4ad9ae07a1faa01a3199
Complete output (9 lines):
Traceback (most recent call last):
File "", line 1, in
File "C:\Users\bibi\AppData\Local\Temp\pip-install-ma3x6o5s\pytorch-fid_20cb67d1201c4ad9ae07a1faa01a3199\setup.py", line 34, in
packages=setuptools.find_packages(where='src/'),
File "C:\Users\bibi\anaconda3\lib\site-packages\setuptools_init_.py", line 64, in find
convert_path(where),
File "C:\Users\bibi\anaconda3\lib\distutils\util.py", line 112, in convert_path
raise ValueError("path '%s' cannot end with '/'" % pathname)
ValueError: path 'src/' cannot end with '/'
----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Can you please help?

**Comment by KritR** [comment]
This does seem to occur with me as well, I'm going to assume this is only a problem on windows because running the equivalent on Linux seems to work fine.

**Comment by KritR** [comment]
If you want to install it anyway, it should be easy enough to go to this line in setup.py and replace 'src/' with 'src'

```
- 34       packages=setuptools.find_packages(where='src/'),
+ 34       packages=setuptools.find_packages(where='src'),
```

And then run `python setup.py install`.

**Comment by mseitzer** [comment]
Fixed with #55. Thanks for the fix!

**Comment by Dok11** [comment]
I have same issue now.

```
E:\Projects\lightweight-gan>pip install pytorch-fid
Collecting pytorch-fid
  Using cached pytorch-fid-0.2.0.tar.gz (11 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\oleg\AppData\Local\Continuum\anaconda3\envs\lightweight-gan\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\oleg\\AppData\\Local\\Temp\\pip-install-r32w79_z\\pytorch-fid_d0b8c9840f06418f9e0d0b18d171018e\\setup.py'"'"'; __file__='"'"'C:\\Users\\oleg\\AppData\\Local\\Temp\\pip-install-r32w79_z\\pytorch-fid_d0b8c9840f06418f9e0d0b18d171018e\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\oleg\AppData\Local\Temp\pip-pip-egg-info-94eqfdgq'
         cwd: C:\Users\oleg\AppData\Local\Temp\pip-install-r32w79_z\pytorch-fid_d0b8c9840f06418f9e0d0b18d171018e\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\oleg\AppData\Local\Temp\pip-install-r32w79_z\pytorch-fid_d0b8c9840f06418f9e0d0b18d171018e\setup.py", line 34, in <module>
        packages=setuptools.find_packages(where='src/'),
      File "C:\Users\oleg\AppData\Local\Continuum\anaconda3\envs\lightweight-gan\lib\site-packages\setuptools\__init__.py", line 64, in find
        convert_path(where),
      File "C:\Users\oleg\AppData\Local\Continuum\anaconda3\envs\lightweight-gan\lib\distutils\util.py", line 124, in convert_path
        raise ValueError("path '%s' cannot end with '/'" % pathname)
    ValueError: path 'src/' cannot end with '/'
```

**Comment by Dok11** [comment]
But this working `pip install git+https://github.com/mseitzer/pytorch-fid.git`
