### ISSUE TITLE
Please tell why:ValueError: path 'src/' cannot end with '/'

### ISSUE THREAD

**Issue by ChauvinisticJonatha** [mseitzer/pytorch-fid#56]

**Comment by ChauvinisticJonatha** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mseitzer"<notifications@github.com&gt;; 
发送时间: 2020年12月11日(星期五) 下午4:45
收件人: "mseitzer/pytorch-fid"<pytorch-fid@noreply.github.com&gt;; 
抄送: "张占杰"<1097234580@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [mseitzer/pytorch-fid] Please tell why:ValueError: path &#39;src/&#39; cannot end with &#39;/&#39; (#56)





 
This is a problem under Windows. It was fixed with #55, but is not in the pypi package yet. You can install from Github in the meantime:
 
pip install git+https://github.com/mseitzer/pytorch-fid.git

**Comment by lilala0** [comment]
Maybe you can refer to the solution here：https://blog.csdn.net/woaichixiaodangao/article/details/108325973
