### ISSUE TITLE
concerning file paths and pickles

### ISSUE THREAD

**Issue by mindblowingaiart** [mseitzer/pytorch-fid#68]
for calculating the fid score, would you want to set the file path to the folders that contain the initialized .pkl file and the trained .pkl file in the other folder?

**Comment by mseitzer** [comment]
What .pkl files are you referring to? If you are talking about the pretrained statistics, these are .npz files, and it does not matter in which folder they are.

**Comment by mindblowingaiart** [comment]
Hi I want to find out the fid score of my trained stylegan models. There is the stylegan model before training, and one after and I want to figure out the difference between them or how accurate the training is.

**Comment by mseitzer** [comment]
I can not help you with this. Please ask the author of the stylegan model you are using.
