### ISSUE TITLE
Data folders for computing

### ISSUE THREAD

**Issue by vinduon** [mseitzer/pytorch-fid#74]
I have a question about this repo:
+ Should be 2 folders have similar image resolution?
+ If not, should we resize it by PIL or torch transforms resize?
Thank you

**Comment by mseitzer** [comment]
- The folders do not have to have the same resolution (but each image in each folder should have the same resolution)
- The code automatically resizes images to the size required by the network.

In general, image resizing and FID is a tricky topic, see https://arxiv.org/abs/2104.11222.

**Comment by duongquangvinh** [comment]
Thank you so much for your reply.

I do not know that if my data_folder_1 has all PNG images and data_folder_2 has all JPG images, does the score make sense?
