### ISSUE TITLE
python: symbol lookup error: /home/xxx/miniconda3/envs/torch/lib/python3.7/site-packages/mk│ l/../../../libmkl_intel_thread.so.1: undefined symbol: __kmpc_global_thread_num

### ISSUE THREAD

**Issue by bridgeqiqi** [mseitzer/pytorch-fid#86]
Hi, I came across this issue when run this command `python -m pytorch_fid /path1 /path2`.

Could anyone help me to resolve this issue?

Thanks

**Comment by mseitzer** [comment]
This seems to be an issue related to your environment configuration. Try to recreate the environment, or try creating an environment using pip instead of conda to see if the error persists.
