### ISSUE TITLE
RuntimeError: unexpected EOF, expected 877244 more bytes. The file might be corrupted.

### ISSUE THREAD

**Issue by yoolish** [mseitzer/pytorch-fid#87]
I met this error when i implemented it.

RuntimeError: unexpected EOF, expected 877244 more bytes. The file might be corrupted.

**Comment by cyyycc** [comment]
> I met this error when i implemented it.
> 
> RuntimeError: unexpected EOF, expected 877244 more bytes. The file might be corrupted.

我也遇到了同样的问题，请问你解决了吗？

**Comment by cyyycc** [comment]
> > I met this error when i implemented it.
> > RuntimeError: unexpected EOF, expected 877244 more bytes. The file might be corrupted.
> 
> 我也遇到了同样的问题，请问你解决了吗？
是因为权重下载中断了，删除原来的权重，重新再下载一遍就可以了
