### ISSUE TITLE
Error while loading weights from url

### ISSUE THREAD

**Issue by lthilnklover** [mseitzer/pytorch-fid#99]
Hi, I'm currently using pytorch-fid to evaluate the generative models. However, from time to time, I got the following error:

`RuntimeError: storage has wrong byte size: expected %ld got %ld0768`
 
while loading weights from url. If I try to download the file directly from the FID_WEIGHTS_URL, it works. So I don't think the link itself is the problem. Did anybody face the similar issue?

**Comment by mseitzer** [comment]
This sounds like a corrupted download of the checkpoint file. Delete the checkpoint and try again.
